### PR TITLE
Fixing a few issues

### PR DESCRIPTION
**Pull request by Naereen**
Hi,
Using the latest version of gym (0.9.7), I ran into some issues with `gym.benchmark_spec` being undefined. I think it was removed from the codebase since you wrote your project.

I fixed the `run-atari.py` script to manually use `Breakout-v0` env instead of using the `gym.benchmark_spec` module.

This PR also fixes a few spelling typos, as well as generalizing the default action space for any NES environment (for games others than this Soccer example, the left key is useful! its better to show the complete list of possible actions).

I also reduce the default memory needed to run the demo, as `replay_buffer_size=1000000` is actually a lot.

Finally, it added one comment in the `nes_interface.lua` to highlight where to comment/uncomment if one wants the "human" speed and not the maximum speed.

### CODE REVIEW

**Comment by codescv** [comment]
Thank you very much for your contribution!
One little problem, could you switch your git commit messages to English so that I can understand?
Thanks!

**Comment by Naereen** [comment]
I think I added too many commits on this PR, sorry.
I'm not sure how to only include the first fews.

**Comment by codescv** [comment]
You can use git rebase -i to squash all the commits into one, and rewrite the message.

See this example:
https://gist.github.com/landsman/d9d2b5fd03b0a3fff0c26603f3360987

**Comment by Naereen** [comment]
I deleted my fork too soon, too bad.

**Pull request closed without merging**
